global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "fx_custom_exporter"
    static_configs:
      - targets: ["fx_custom_exporter:8000"]
